#pragma once

#include <array>
#include <memory>
#include <vector>

#include <AL/al.h>

#include "Audio/Resources/AudioClip.h"
#include "Audio/Streaming/IStreamDecoder.h"
#include "Core/Types/Numeric.h"

namespace Blackthorn::Audio {

/**
 * @brief Per-voice state for double-buffered streaming playback.
 *
 * One @c StreamingVoiceState is created by
 * @c AudioThread::processStreamingPlayback() and attached to a @c Voice via
 * @c Voice::attachStreamingState(). It is destroyed when the voice is
 * released via @c Voice::reset().
 *
 * @section decoder_ownership Decoder ownership
 * The decoder is owned here, not on @c StreamingAudioClip. Each active
 * streaming voice holds its own @c IStreamDecoder, opened against the clip's
 * source path when the voice is activated.
 *
 * @section double_buffering Double buffering
 * Two OpenAL buffer objects (@c alBuffers) are allocated by @c init() and
 * deleted by the destructor. The audio thread rotates between them each tick:
 *
 *   1. @c alSourceUnqueueBuffers recovers any buffer the mixer has consumed
 *      → pushed onto @c freeBuffers.
 *   2. If @c pendingUpload has data and @c freeBuffers is non-empty, upload
 *      the pending samples into @c freeBuffers.back(), queue it, clear
 *      @c pendingUpload, and submit the next decode job.
 *   3. @c StreamBufferReadyCommand arrives: if @c freeBuffers is non-empty,
 *      upload immediately. If not, move samples into @c pendingUpload.
 *
 * @section pending_upload Pending upload
 * @c pendingUpload holds decoded samples that arrived before the AL mixer
 * returned a free buffer. Unlike the old @c pendingChunk design, the flush
 * is driven by the audio thread's tick loop via @c tickStreaming(), not by
 * an incoming command. This means a stalled pending upload is always
 * resolved on the very next tick once a buffer becomes free, no incoming
 * command is needed to unblock it.
 *
 * @section end_of_stream End-of-stream drain
 * When the streaming thread signals @c endOfStream, the audio thread sets
 * @c endOfStream. @c VoicePool::update() releases the voice once
 * @c isStopped() is also true (the AL queue has fully drained).
 */
struct StreamingVoiceState {
	StreamingVoiceState() = default;

	/**
	 * @brief Closes the decoder and deletes the two AL buffer objects.
	 *
	 * Must run on the audio thread.
	 */
	~StreamingVoiceState();

	StreamingVoiceState(const StreamingVoiceState&) = delete;
	StreamingVoiceState& operator=(const StreamingVoiceState&) = delete;

	/**
	 * @brief Generates the two AL buffer objects and populates @c freeBuffers.
	 *
	 * Must be called exactly once, on the audio thread, after @c decoder is
	 * set and before any @c readFrames call.
	 */
	void init();

	[[nodiscard]]
	U64 lookupBufferFrames(ALuint bufferId) const noexcept {
		for (const auto& [id, count] : bufferFrameCounts) {
			if (id == bufferId)
				return count;
		}

		return 0;
	}

	void recordBufferFrames(ALuint bufferId, U64 frames) noexcept {
		for (auto& [id, count] : bufferFrameCounts) {
			if (id == bufferId || id == 0) {
				id = bufferId;
				count = frames;
				return;
			}
		}
	}

	/// The two AL buffer objects. Generated by @c init(), deleted by dtor.
	std::array<ALuint, 2> alBuffers = { 0, 0 };

	/// AL buffer IDs ready to be filled and re-queued. After pre-fill this
	/// is empty (both buffers are queued). Replenished by
	/// @c unqueueProcessedBuffers each tick.
	std::vector<ALuint> freeBuffers;

	/// Maps each AL buffer ID to the frame count last uploaded into it
	std::array<std::pair<ALuint, U64>, 2> bufferFrameCounts = {
		std::pair<ALuint, U64>{ 0, 0 },
		std::pair<ALuint, U64>{ 0, 0 }
	};

	/// @c AL_FORMAT_MONO16 or @c AL_FORMAT_STEREO16.
	ALenum format = 0;

	/// Sample rate in Hz.
	U32 sampleRate = 0;

	/**
	 * @brief Decoded samples waiting for a free AL buffer.
	 *
	 * Set by @c process(StreamBufferReadyCommand) when no free buffer is
	 * available. Flushed by @c AudioThread::tickStreaming() on the next tick
	 * once @c unqueueProcessedBuffers recovers a buffer. The streaming thread
	 * is kept idle (no new job submitted) while this is non-empty, so at most
	 * one chunk can ever be pending at a time.
	 */
	std::vector<I16> pendingUpload;

	/**
	 * @brief Whether @c pendingUpload carries an end-of-stream marker.
	 *
	 * Consumed alongside @c pendingUpload when it is flushed.
	 */
	bool pendingEndOfStream = false;

	/**
	 * @brief True once the streaming thread has signalled end-of-stream.
	 *
	 * After this is set, no further decode jobs are submitted.
	 * @c VoicePool::update() releases the voice once the AL queue drains.
	 */
	bool endOfStream = false;

	/**
	 * @brief The decoder for this voice instance.
	 *
	 * Opened by @c processStreamingPlayback() on the audio thread.
	 * Read by the streaming thread during jobs. Touched by the audio thread
	 * for loop-seek and teardown, always non-concurrent with streaming
	 * thread access by design.
	 */
	std::unique_ptr<Streaming::IStreamDecoder> decoder;

	/**
	 * @brief Non-owning pointer back to the owning @c StreamingAudioClip.
	 *
	 * Used only by @c process(ReloadStreamingClipCommand) to identify
	 * voices to interrupt. Never dereferenced for audio data.
	 */
	const AudioClip* sourceClip = nullptr;
};


} // namespace Blackthorn::Audio