#pragma once

#include <variant>
#include <vector>

#include <glm/glm.hpp>

#include "Audio/AudioCategory.h"
#include "Audio/AudioHandle.h"
#include "Audio/Resources/AudioClip.h"
#include "Core/Types/Numeric.h"

namespace Blackthorn::Audio {
/**
 * @brief Starts playback of a new voice.
 *
 * The @c handle is pre-generated by @c AudioManager on the game thread.
 * Stale handle detection relies on the never-reused monotonic ID.
 */
struct PlayCommand {
	AudioHandle handle;
	AudioClip* clipSource = nullptr;

	float volume = 1.0f;
	float pitch = 1.0f;

	AudioCategory category = AudioCategory::SFX;
	int priority = 0;

	bool loop = false;
	bool spatial = false;

	glm::vec3 position{ 0.0f };

	float minDistance = 1.0f;
	float maxDistance = 50.0f;
	float clipDuration = 0.0f;
};

struct PauseCommand {
	AudioHandle handle;
};

struct ResumeCommand {
	AudioHandle handle;
};

struct StopCommand {
	AudioHandle handle;
};

struct SetVolumeCommand {
	AudioHandle handle;
	float volume = 1.0f;
};

struct SetPitchCommand {
	AudioHandle handle;
	float pitch = 1.0f;
};

struct SetPositionCommand {
	AudioHandle handle;
	glm::vec3 position{ 0.0f };
};

struct SetCategoryVolumeCommand {
	AudioCategory category = AudioCategory::SFX;
	float volume = 1.0f;
};

struct ListenerTransformCommand {
	glm::vec3 position{ 0.0f };
	glm::vec3 forward{ 0.0f, 0.0f, -1.0f };
	glm::vec3 up{ 0.0f, 1.0f, 0.0f };
	glm::vec3 velocity{ 0.0f };
};

struct StopAllCommand {};


/**
 * @brief Delivers a decoded PCM chunk from the streaming thread.
 */
struct StreamBufferReadyCommand {
	AudioHandle handle;
	std::vector<I16> samples;
	U32 channels = 0;
	U32 sampleRate = 0;
	bool endOfStream = false;
};

using AudioCommand = std::variant<
	PlayCommand,
	StopCommand,
	PauseCommand,
	ResumeCommand,
	SetVolumeCommand,
	SetPitchCommand,
	SetPositionCommand,
	SetCategoryVolumeCommand,
	StopAllCommand,
	ListenerTransformCommand,
	StreamBufferReadyCommand
>;

} // namespace Blackthorn::Audio